### ISSUE TITLE
open FPGA issues

### ISSUE THREAD

**Issue by arrenglover** [event-driven-robotics/event-driven-demos#6]
Hi @mcasti-iit 

As I understand there are still some open issues with the FPGA and the Gen 3 upgrade on the robot.

- [x] bars of blank areas at the edges of the sensor
- [x] not 100% reliable and sometimes needs restarting
- [x] unstable operation when turning on and off a camera. it seems okay to be done from the command line, directly writing the registers, but does not work from zynqGrabber, this could be a zynqGrabber problem.

Can you please give an update on these issues? Do we know the cause? Is there a fix?

**Comment by mcasti-iit** [comment]
Hi @arrenglover;

the bars of blank aeras (I saw them only sometimes) seem not to be depending from FPGA data handling. We performed test about that, and every data produced as test is correctly received through HPU Core. I can indagate deeper in order to understand if it depends on GEN3 chip itself.

The problem of "restarting" depends on relationship between clocks, and sometimes it brokes the data capturing. It is very hard to solve because there aren't informations about clock behaviour on GEN3 data sheet, anyway there is a specific register (0x51 - GEN3_PHASE_ALIGN, default value 0xA0) able to change the sampling point of GEN3 data and solve the problem at every restart.
I mean: you can restart in order to have the "correct" data sampling with default value 0xA0, or you can change that value in that register (as explained after installing GEN3 on the robot).

About unstable operation, I think we should analyse the sequence of operation performed by zynqGrabber to solve.

**Comment by arrenglover** [comment]
Thanks very much @mcasti-iit for the update :smile: 

I think that if we work on point 3 first (unstable turn on/off) we might find a bug in zynqGrabber when trying to program the registers. It may be that the same bug could be causing problems for point 1 and 2 - therefore we can re-evaluate points 1 and 2 again after fixing point 3.

- [ ] @arrenglover fix zynqGrabber for turn-on/turn off. Organise with @mcasti-iit if help is needed. Scheduled: 1 March 2023

**Comment by mcasti-iit** [comment]
Hi @arrenglover;
the item #2, related to the "ghost effect" that used to appear sometimes, seems to be solved

**Comment by arrenglover** [comment]
thanks @mcasti-iit !

**Comment by arrenglover** [comment]
bars at blank areas of screen was a bug in setting the ROI

**Comment by arrenglover** [comment]
- [ ] add skin controller to ZG2
 - [x] add sensitivity as command line option
 - [ ] add ROI specification to ZG2 (currently always full retina)
 - [x] add turn/off handling properly
 - [x] make start_clock automatic
